apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: faceapi2

resources:
  - ../../namespace.yaml
  - storage.yaml
  - ../../mqtt.yaml
  - ../../api.yaml
  - ../../monitoring.yaml
  - ../../face-md.yaml
  - ../../face-pp.yaml
  - ../../jobs.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: faceapi2

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: faceapi2-secrets
    envs:
      - shared-docker-data.secrets.env

configMapGenerator:
  - name: faceapi2-app-config
    envs:
      - shared-docker-data.env
  - name: mosquitto-config
    files:
      - ../../mosquitto.conf
  - name: prometheus-config
    files:
      - ../../prometheus.yml
      - ../../alerts.yml
  - name: alertmanager-config
    files:
      - ../../alertmanager.yml
  - name: loki-config
    files:
      - ../../loki-config.yml
  - name: grafana-datasources
    files:
      - datasources.yml=../../grafana-datasources.yml
  - name: grafana-dashboard-provider
    files:
      - dashboards.yml=../../grafana-dashboard-provider.yml
  - name: grafana-dashboard-json
    files:
      - faceapi-overview.json=../../grafana-dashboard-faceapi-overview.json
  - name: promtail-config
    files:
      - ../../promtail-config.yml

patches:
  - path: patch-register-faces-job.yaml
