apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "faceapi2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  selector:
    app: api
  ports:
    - name: http
      port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    {{- include "faceapi2.labels" . | nindent 4 }}
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: {{ .Values.service.mysql.port }}
      targetPort: {{ .Values.service.mysql.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    {{- include "faceapi2.labels" . | nindent 4 }}
spec:
  selector:
    app: mongo
  ports:
    - name: mongo
      port: {{ .Values.service.mongo.port }}
      targetPort: {{ .Values.service.mongo.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt
  labels:
    {{- include "faceapi2.labels" . | nindent 4 }}
spec:
  selector:
    app: mqtt
  ports:
    - name: mqtt
      port: {{ .Values.service.mqtt.port }}
      targetPort: {{ .Values.service.mqtt.port }}
    - name: mqtt-ws
      port: {{ .Values.service.mqtt.websocketPort }}
      targetPort: {{ .Values.service.mqtt.websocketPort }}
